### PR TITLE
package.json: update file-uploader plugin to v0.0.4.

### LINKED ISSUE #246: Error Couldn't upload file: file.text/html; charset=utf-8
When I try to insert application/rtf content that contains a link, ckeditor tries to download the contents of the link and upload it to the server, which causes the error "Couldn't upload file: file.text/html; charset=utf-8" How can I make ckeditor not try to download, but simply insert rtf?
изображение_2024-09-13_151104953

### PR DESCRIPTION
**Pull request by goapunk**
fixes #246

### CODE REVIEW

**Comment by hvlads** [comment]
Hi @goapunk 

Thank you for your pull request! I appreciate your contribution. However, I noticed that your plugin relies on specific versions of CKEditor 5, which restricts my ability to update the CKEditor packages in the django-ckeditor-5 project.

Due to this, I have temporarily removed your plugin from the code. If you could adjust the dependencies to allow for version flexibility, it would be greatly appreciated.

Thank you!

**Comment by goapunk** [comment]
@hvlads I will look into it, however relaxing the version requirements might not work as far as I remember. If you check for example the ckeditor image plugin it also pins the dependencies to a specific version: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-image/package.json

**Comment by goapunk** [comment]
@hvlads I updated the plugin with more relaxed requirements, it works again now

**Comment by hvlads** [comment]
> @hvlads I updated the plugin with more relaxed requirements, it works again now

The problem is that when I update CKEditor, all the packages included in it need to have the same version. However, your plugin would still use the old version, which could cause issues.

**Pull request merged**
