### PR TITLE
Update the event handler to avoid sending the event to the createEditor function

### PR DESCRIPTION
**Pull request by frague59**
For compatibility with [django-content-editor](https://github.com/feincms/django-content-editor), fix a bug in the `formset:added` process in CKEditor apps.js 
The PR also rollback previous PR attempt.

### CODE REVIEW

**Comment by frague59** [comment]
No, we do not need it.

**Comment by frague59** [comment]
As this PR rollbacks the first commit, it can be merged, no ?

**Comment by goapunk** [comment]
> As this PR rollbacks the first commit, it can be merged, no ?

It just adds an unnecessary commit to the history, so it's nicer if we remove it. I think @hvlads can edit the PR and remove it maybe.

**Comment by hvlads** [comment]
Hi @frague59 
Thank you for your pull request! I noticed that there are a lot of formatting changes due to your editor, while the significant change is only in one line of code.

Could you please explain how your code addresses the issue? Additionally, I would appreciate it if you could create a separate pull request with just the modifications to that one line where you changed the function. This will help keep the history cleaner and make it easier to review.

Thank you for your understanding!

**Comment by hvlads** [comment]
Hi  @frague59 ,

Could you please create a new pull request with changes only in the specific line that resolves your issue?

Thank you!

**Pull request closed without merging**
