### PR TITLE
pyproject.toml: Add config settings

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by hvlads** [comment]
You can use this file https://github.com/hvlads/django-ckeditor-5/blob/master/requirements_dev.txt

**Comment by cclauss** [comment]
The flake8 folks are just being padantic... https://github.com/PyCQA/flake8/issues/234

**Comment by cclauss** [comment]
Ready for your review.

**Comment by hvlads** [comment]
thank you! Good job!

**Pull request merged**
